---
title: "Simulate traits"
author: "Frederick J. Boehm"
date: "9/25/2019"
output: html_document
---

```{r saveRDS}
if (!file.exists(here::here("data", "derived_data", "genoprobs.rds"))){
  download.file("https://datadryad.org/stash/downloads/file_stream/63306",
              destfile = here::here("data", "raw_data", "Attie_DO378_eQTL_viewer_v1.Rdata")
              )
  load(here::here("data", "raw_data", "Attie_DO378_eQTL_viewer_v1.Rdata"))
  saveRDS(dataset.islet.rnaseq$lod.peaks, here::here("data", "derived_data", "lod_peaks.rds"))
  saveRDS(dataset.islet.rnaseq$annots, here::here("data", "derived_data", "annots.rds"))
  saveRDS(dataset.islet.rnaseq$expr, here::here("data", "derived_data", "expr.rds"))
  saveRDS(K, here::here("data", "derived_data", "kinship.rds"))
  saveRDS(map, here::here("data", "derived_data", "map.rds"))
  saveRDS(genoprobs, here::here("data", "derived_data", "genoprobs.rds"))
  saveRDS(dataset.islet.rnaseq$covar, here::here("data", "derived_data", "covar.rds"))
}
```

```{r readRDS}
lod_peaks <- readRDS(here::here("data", "derived_data", "lod_peaks.rds"))
annots <- readRDS(here::here("data", "derived_data", "annots.rds"))
expr <- readRDS(here::here("data", "derived_data", "expr.rds"))
probs <- readRDS(here::here("data", "derived_data", "genoprobs.rds"))
K <- readRDS(here::here("data", "derived_data", "kinship.rds"))
covar <- readRDS(here::here("data", "derived_data", "covar.rds"))
map <- readRDS(here::here("data", "derived_data", "map.rds"))
```